language: c

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang


script:
  - mkdir $TRAVIS_BUILD_DIR/build
  - cd $TRAVIS_BUILD_DIR/build
  - CFLAGS="-g -Wall -Wextra -Werror -Wno-zero-length-array" cmake ..
  - make
